### PR TITLE
Try pinning to 38

### PR DESCRIPTION
**Pull request by justaddcoffee**

### CODE REVIEW

**Comment by justaddcoffee** [comment]
I wonder why github actions is not running

**Comment by glass-ships** [comment]
out of curiosity, does it build for you locally?

**Comment by justaddcoffee** [comment]
>  out of curiosity, does it build for you locally?

Yep, `cargo build` completes on my M1 Mac

**Comment by glass-ships** [comment]
curious... it was building for me too on my ubuntu machine before this metric update. 
were there any changes to semsimian itself that could have to do with it? 
or is it likely something in the server code that we changed?

**Comment by justaddcoffee** [comment]
> curious... it was building for me too on my ubuntu machine before this metric update. were there any changes to semsimian itself that could have to do with it? or is it likely something in the server code that we changed?

Can you paste the stack trace from cargo build failure on your local machine? Is it a py03 library problem?

**Comment by glass-ships** [comment]
same error the GH action is getting: 
```
...
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `semsimian_server` (bin "semserver") due to previous error
```

**Pull request closed without merging**
