### PR TITLE
PR with a working build

### PR DESCRIPTION
**Pull request by justaddcoffee**

### CODE REVIEW

**Comment by justaddcoffee** [comment]
@hrshdhgd @glass-ships @kevinschaper @caufieldjh 

FWIW here is a branch with a working build, see [here](https://github.com/monarch-initiative/semsimian-server/actions/runs/8268474018/job/22621430441?pr=16)

**Comment by hrshdhgd** [comment]
Awesome!! Try cargo tests

**Comment by caufieldjh** [comment]
So the issue is fixed by running `actions/setup-python@v2`?
Or is it specifically because it installs python 3.12.2?
I'm puzzled as to why this worked before without a python install step.
(oh, of course it's because python is already available, and somehow was previously compatible)

**Comment by hrshdhgd** [comment]
My guess is the code changes outside the files here are responsible for the errors.

**Comment by justaddcoffee** [comment]
Not sure why exactly this is working and the other PRs are not

It should be possible to merge stuff from the other branch into this PR and figure out what is breaking this build

**Comment by justaddcoffee** [comment]
Also, this branch is identical to `monarch-initiative:add-semsimian-metric` (where the CI is failing), which would tend to indicate that this problem is something to do with how github is executing this CI?

**Comment by hrshdhgd** [comment]
> Also, this branch is identical to `monarch-initiative:add-semsimian-metric` (where the CI is failing)

I doubt it. Your PR does not show changes in the `bin.rs` and `lib.rs` files

**Comment by justaddcoffee** [comment]
> > Also, this branch is identical to `monarch-initiative:add-semsimian-metric` (where the CI is failing)
> 
> I doubt it. Your PR does not show changes in the `bin.rs` and `lib.rs` files

hmm, strange - why then when I try to change the base to  `monarch-initiative:add-semsimian-metric` in the UI does github tell me:
> "There are no new commits between base branch 'add-semsimian-metric' and head branch 'test_build'"

**Comment by hrshdhgd** [comment]
I did not follow what you meant there.

**Comment by glass-ships** [comment]
> which would tend to indicate that this problem is something to do with how github is executing this CI?

i'm also suspicious of this, as i'm getting the same errors locally where i do have `python3` and `python3-dev` installed, and was able to build before this release

**Comment by glass-ships** [comment]
i took a look at the files in your fork at this branch; i think the reason this PR is able to build is because it's based on main, which is also able to build, as it doesn't include any of the changes made in [this branch](https://github.com/monarch-initiative/semsimian-server/tree/add-semsimian-metric), and is still using:
```
# from cargo.lock
[[package]]
name = "semsimian"
version = "0.2.12"
``` 
which suggests to me that the issue is rooted either in the latest rc of semsimian, or in the code changes we made to bin.rs or lib.rs.

i'd be curious if the same GH Action changes from here made in #12 would work - i can give that a shot, though i'm not too hopeful

**Comment by justaddcoffee** [comment]
Ah okay, thanks @glass-ships @hrshdhgd  - I think this PR might be confusing things (my fault), so I'm going to close it

**Pull request closed without merging**
