### PR TITLE
first_match is not None anymore!

### PR DESCRIPTION
**Pull request by hrshdhgd**
I added to your test code @glass-ships 

I also ran `cargo fmt` which formats the code and hence the other 2 files have changed. Its just formatting.

### CODE REVIEW

**Review by glass-ships — APPROVED** [review]
oh awesome, thanks so much for working on this!

**Comment by glass-ships** [comment]
i also realized tests are going to fail here regardless because phenio doesn't exist in the runner. 

so i've been fighting with trying to get the server to download the gz and decompress it if it doesn't exist, but. no luck so far

**Comment by hrshdhgd** [comment]
Usually what we do is use a very small db file for testing. For semsimian we have the [go-nucleus.db](https://github.com/monarch-initiative/semsimian/blob/main/tests/data/go-nucleus.db) file. Feel free to use it. Some parts of the test will change (obv)

**Comment by glass-ships** [comment]
oh nice! yeah that's probably a better use of my time, then

**Pull request merged**
